spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: # enter your email id #
    password:   # enter your email app password #
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


